apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: feature-flag-dev
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: analytics-service
        image: 964177143569.dkr.ecr.us-east-1.amazonaws.com/feature-flag-analytics-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: PORT
          value: "8005"
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_REGION
        - name: AWS_SQS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SQS_URL
        - name: AWS_DYNAMODB_TABLE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_DYNAMODB_TABLE
        - name: DISABLE_AWS
          value: "false"
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: feature-flag-dev
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
  - port: 8005
    targetPort: 8005
